# Generated by Django 5.2.7 on 2025-10-17 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del negocio o ubicación', max_length=200, verbose_name='Nombre del negocio')),
                ('categoria', models.CharField(help_text='Categoría del negocio (ej: Restaurante, Cafetería, Hotel)', max_length=100, verbose_name='Categoría')),
                ('direccion', models.TextField(help_text='Dirección completa de la ubicación', verbose_name='Dirección')),
                ('lat', models.DecimalField(decimal_places=6, help_text='Latitud de la ubicación (coordenada geográfica)', max_digits=10, verbose_name='Latitud')),
                ('lng', models.DecimalField(decimal_places=6, help_text='Longitud de la ubicación (coordenada geográfica)', max_digits=10, verbose_name='Longitud')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Marcador',
                'verbose_name_plural': 'Marcadores',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['lat', 'lng'], name='markers_mar_lat_74bc7e_idx'), models.Index(fields=['categoria'], name='markers_mar_categor_df1e2c_idx')],
            },
        ),
    ]
