# Generated by Django 5.2.7 on 2025-10-17 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marker',
            name='lat',
            field=models.DecimalField(decimal_places=9, help_text='Latitud de la ubicación (coordenada geográfica)', max_digits=12, verbose_name='Latitud'),
        ),
        migrations.AlterField(
            model_name='marker',
            name='lng',
            field=models.DecimalField(decimal_places=9, help_text='Longitud de la ubicación (coordenada geográfica)', max_digits=12, verbose_name='Longitud'),
        ),
    ]
